# Generated by Django 4.1.1 on 2022-09-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=50)),
                ("stype", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("no_services", models.IntegerField()),
                (
                    "image",
                    models.ImageField(default="images/img1.jpg", upload_to="images"),
                ),
                ("description", models.CharField(default="", max_length=1000)),
            ],
        ),
    ]
