# Generated by Django 4.1.1 on 2022-09-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=35)),
                ("password", models.CharField(max_length=15)),
                ("role", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "loginid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="userapp.login"
                    ),
                ),
            ],
        ),
    ]
