# Generated by Django 4.1.1 on 2022-09-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_num", models.CharField(max_length=14)),
                ("cvv", models.IntegerField()),
                ("expiry", models.CharField(max_length=7)),
                ("booking_date", models.CharField(max_length=14)),
                ("slots", models.CharField(max_length=10)),
                ("amount", models.FloatField()),
                ("order_date", models.DateField(default="2022-08-18")),
                ("status", models.IntegerField()),
                (
                    "Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="car.service"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="userapp.login"
                    ),
                ),
            ],
        ),
    ]
